### ISSUE TITLE
I = Squash Bool ?

### ISSUE THREAD

**Issue by andreasabel** [jespercockx/cubes#2]
Andrea pointed me to this reddit:

  https://www.reddit.com/r/agda/comments/4veb5a/irrelevance_rewriting_extensionality/

Can you simplify your encoding a bit if you use I = Squash Bool ?
(Less postulates, maybe.)

**Comment by jespercockx** [comment]
I tried this, but the approach seems to fall apart because Agda erases the irrelevant stuff too eagerly and hence the remaining rewrite rules don't fire. Here's the attempt:

```
record I : Set where
  constructor squash
  field
    .proof : Bool

₀ : I
₀ = squash false

₁ : I
₁ = squash true

.reparam : Bool → Bool → Bool → Bool
reparam false y z = y
reparam true  y z = z

_[_-_] : I → I → I → I
squash x [ squash y - squash z ] = squash (reparam x y z)

data _─_ {ℓ} {A : Set ℓ} : A → A → Set ℓ where
  path : (M : I → A) → M ₀ ─ M ₁

_$_ : ∀ {ℓ} {A : Set ℓ} {a b : A} → a ─ b → I → A
path M $ i = M i

coerce : ∀ {ℓ} {S T : Set ℓ} (Q : S ─ T) (p q : I) → Q $ p → Q $ q
coerce (path M) (squash _) (squash _) x = x
```

As you can see, coercion can be implemented as the identity, which is definitely _not_ what we want (maybe for OTT this would be fine, but for anything higher-dimensional it's not).

Maybe it would work if we had shape-irrelevant record fields...

**Comment by jespercockx** [comment]
And it seems to work with shape irrelevance: https://github.com/jespercockx/cubes/blob/976c7bc6b5fe1cde9d0ffbc2cf549499fee606c5/Cubes.agda

It's quite annoying without the shape irrelevant fields, though.

**Comment by andreasabel** [comment]
You could add them to the parser.

**Comment by jespercockx** [comment]
Done! It now seems to work: https://github.com/jespercockx/cubes/commit/0aa69c35ad3f98efce9f4e616928411873ca865e

Edit: forgot to remove the .. from the previous attempt
